server:
  port: 8081

spring:
  application:
    name: scrumMaster-api

  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: NEVER
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_URL}:5432/postgres
    username: ${DB_USERNAME}
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}
    show-sql: false
